alter table products
add constraint prd_fk_cat foreign key(category_id) references category (category_id)

alter table orders
add constraint ord_fk_cust foreign key(customer_id) references customers(customer_id)

alter table orders
add constraint ord_fk_sellers foreign key (seller_id) references sellers(seller_id)

alter table order_items
add constraint orditems_fk_ord foreign key (order_id) references orders(order_id)

alter table order_items
add constraint orditems_fk_prod foreign key (product_id) references products(product_id)

alter table payments 
add constraint payment_fk_ord foreign key (order_id) references orders(order_id)

alter table shipping
add constraint ship_fk_ord foreign key (order_id) references orders(order_id)

alter table inventory
add constraint inven_fk_pro foreign key (product_id) references products(product_id)
---EDA
select * from category
select * from customers
select * from inventory
select * from order_items
select * from orders
select * from payments
select * from products
select * from sellers
select * from shipping

select distinct payment_status from payments

select * from shipping 
where return_date is not null

--To checking the order_id is proparly reurned or not returned
select * from shipping 
where order_id = 6747

select * from payments
where order_id = 6747

select * from shipping
where return_date is null

--Business problems
/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

-- Step 1: Add total_sale column to order_items table
alter table order_items
add total_sale float;

-- Step 2: Update total_sale = quantity * price_per_unit
update order_items
set total_sale = quantity * price_per_unit;

-- Step 3: Query top 10 products by total sales value
select 
    oi.product_id,
    p.product_name,
    sum(oi.quantity) as total_quantity_sold,
    sum(oi.total_sale) as total_sales_value
from orders o
join order_items oi on o.order_id = oi.order_id
join products p on oi.product_id = p.product_id
group by oi.product_id, p.product_name
order by total_sales_value desc
OFFSET 0 rows fetch next 10 rows ONLY; 

/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

SELECT 
    p.category_id,
    c.category_name,
    SUM(oi.total_sale) AS total_revenue,
    ROUND(
        SUM(oi.total_sale) * 100.0 / 
        (SELECT SUM(total_sale) FROM order_items), 2
    ) AS contribution_percentage
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
LEFT JOIN category c ON p.category_id = c.category_id
GROUP BY p.category_id, c.category_name
ORDER BY total_revenue DESC;

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    ROUND(SUM(oi.total_sale) * 1.0 / COUNT(DISTINCT o.order_id), 2) AS average_order_value,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(DISTINCT o.order_id) > 5
ORDER BY average_order_value DESC;


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/
SELECT 
    year,
    month,
    total_sale AS current_month_sale,
    LAG(total_sale, 1) OVER (ORDER BY year, month) AS last_month_sale
FROM (
    SELECT 
        YEAR(o.order_date) AS year,
        MONTH(o.order_date) AS month,
        ROUND(SUM(oi.total_sale), 2) AS total_sale
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_date >= DATEADD(YEAR, -1, GETDATE())
    GROUP BY YEAR(o.order_date), MONTH(o.order_date)
) AS t
ORDER BY year, month;
---
/*
5.List the customer ID, first name, and last name of customers
who have registered but have never placed an order*/
SELECT 
    c.customer_id,
    c.first_name,
    c.last_name
FROM 
    dbo.customers AS c
LEFT JOIN 
    dbo.orders AS o ON c.customer_id = o.customer_id
WHERE 
    o.order_id IS NULL;


/*
6. Least-Selling Categories by State
 Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/
WITH ranking_table AS (
    SELECT 
        c.state,
        cat.category_name,
        SUM(oi.total_sale) AS total_sale,
        RANK() OVER (PARTITION BY c.state ORDER BY SUM(oi.total_sale) ASC) AS rank
    FROM orders AS o
    JOIN customers AS c ON o.customer_id = c.customer_id
    JOIN order_items AS oi ON o.order_id = oi.order_id
    JOIN products AS p ON oi.product_id = p.product_id
    JOIN category AS cat ON cat.category_id = p.category_id
    GROUP BY c.state, cat.category_name
)

SELECT 
    state,
    category_name,
    total_sale
FROM ranking_table
WHERE rank = 1;


-- 7. Customer Lifetime Value (CLTV)
-- Calculate the total value of orders placed by each customer over their lifetime.
-- Challenge: Rank customers based on their CLTV.

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    SUM(oi.total_sale) AS CLTV,
    DENSE_RANK() OVER (ORDER BY SUM(oi.total_sale) DESC) AS cx_ranking
FROM orders AS o
JOIN customers AS c ON c.customer_id = o.customer_id
JOIN order_items AS oi ON oi.order_id = o.order_id
GROUP BY c.customer_id, c.first_name, c.last_name;


/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT 
	i.inventory_id,
	p.product_name,
	i.stock as current_stock_left,
	i.last_stock_date,
	i.warehouse_id
FROM inventory as i
join 
products as p
ON p.product_id = i.product_id
WHERE stock < 10

-- 9. Shipping Delays
-- Identify orders where the shipping date is later than 3 days after the order date.
-- Challenge: Include customer, order details, and delivery provider.
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS full_name,
    o.order_id,
    o.order_date,
    s.shipping_date,
    s.shipping_providers,
    DATEDIFF(DAY, o.order_date, s.shipping_date) AS days_took_to_ship
FROM orders AS o
JOIN customers AS c ON c.customer_id = o.customer_id
JOIN shipping AS s ON o.order_id = s.order_id
WHERE DATEDIFF(DAY, o.order_date, s.shipping_date) > 3;


/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

-- 10. Payment Success Rate
-- Calculate the percentage of successful payments across all orders.
-- Challenge: Include breakdowns by payment status (e.g., failed, pending).

SELECT 
    p.payment_status,
    COUNT(*) AS total_cnt,
    CAST(COUNT(*) AS NUMERIC) * 100.0 / 
        (SELECT COUNT(*) FROM payments) AS percentage
FROM orders AS o
JOIN payments AS p ON o.order_id = p.order_id
GROUP BY p.payment_status;


/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/

-- 11. Top Performing Sellers
-- Find the top 5 sellers based on total sales value.
-- Challenge: Include both successful and failed orders, and display their percentage of successful orders.

WITH top_sellers AS (
    SELECT 
        s.seller_id,
        s.seller_name,
        SUM(oi.total_sale) AS total_sale,
        RANK() OVER (ORDER BY SUM(oi.total_sale) DESC) AS sales_rank
    FROM orders AS o
    JOIN sellers AS s ON o.seller_id = s.seller_id
    JOIN order_items AS oi ON oi.order_id = o.order_id
    GROUP BY s.seller_id, s.seller_name
),
sellers_reports AS (
    SELECT 
        o.seller_id,
        ts.seller_name,
        o.order_status,
        COUNT(*) AS total_orders
    FROM orders AS o
    JOIN top_sellers AS ts ON ts.seller_id = o.seller_id
    WHERE ts.sales_rank <= 5
      AND o.order_status NOT IN ('Inprogress', 'Returned')
    GROUP BY o.seller_id, ts.seller_name, o.order_status
)

SELECT 
    seller_id,
    seller_name,
    SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END) AS Completed_orders,
    SUM(CASE WHEN order_status = 'Cancelled' THEN total_orders ELSE 0 END) AS Cancelled_orders,
    SUM(total_orders) AS total_orders,
    CAST(SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END) AS NUMERIC) * 100.0 / 
    NULLIF(SUM(total_orders), 0) AS successful_orders_percentage
FROM sellers_reports
GROUP BY seller_id, seller_name;

-- 12. Product Profit Margin
-- Calculate the profit margin for each product.
-- Challenge: Rank products by their profit margin from highest to lowest.

SELECT 
    product_id,
    product_name,
    profit_margin,
    DENSE_RANK() OVER (ORDER BY profit_margin DESC) AS product_ranking
FROM (
    SELECT 
        p.product_id,
        p.product_name,
        CAST(
            (SUM(oi.total_sale - (p.cogs * oi.quantity)) * 100.0) 
            / NULLIF(SUM(oi.total_sale), 0)
            AS NUMERIC(10,2)
        ) AS profit_margin
    FROM order_items AS oi
    JOIN products AS p ON oi.product_id = p.product_id
    GROUP BY p.product_id, p.product_name
) AS t1;


-- 13. Most Returned Products
-- Query the top 10 products by the number of returns.
-- Challenge: Display the return rate as a percentage of total units sold.

SELECT TOP 10
    p.product_id,
    p.product_name,
    COUNT(*) AS total_unit_sold,
    SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned,
    CAST(SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS FLOAT) * 100.0 / 
        NULLIF(COUNT(*), 0) AS return_percentage
FROM order_items AS oi
JOIN products AS p ON oi.product_id = p.product_id
JOIN orders AS o ON o.order_id = oi.order_id
GROUP BY p.product_id, p.product_name
ORDER BY return_percentage DESC;

--14 Inactive Sellers
-- Identify sellers who haven’t made any sales in the last 6 months.
-- Challenge: Show the last sale date and total sales from those sellers.

WITH inactive_sellers AS (
    SELECT *
    FROM sellers
    WHERE seller_id NOT IN (
        SELECT DISTINCT seller_id
        FROM orders
        WHERE order_date >= DATEADD(MONTH, -6, GETDATE())
    )
)

SELECT 
    o.seller_id,
    MAX(o.order_date) AS last_sale_date,
    SUM(oi.total_sale) AS total_sales
FROM orders AS o
JOIN inactive_sellers AS s ON o.seller_id = s.seller_id
JOIN order_items AS oi ON o.order_id = oi.order_id
GROUP BY o.seller_id;


-- 15. Categorize customers as Returning or New based on return count

SELECT 
    customer_id,
    customer_name,
    total_orders,
    total_return,
    CASE
        WHEN total_return > 5 THEN 'Returning_customer'
        ELSE 'New'
    END AS cx_category
FROM (
    SELECT 
        c.customer_id,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_return
    FROM orders AS o
    JOIN customers AS c ON c.customer_id = o.customer_id
    JOIN order_items AS oi ON oi.order_id = o.order_id
    GROUP BY c.customer_id, c.first_name, c.last_name
) AS customer_data;

-- 16. Top 5 Customers by Orders in Each State
-- Identify the top 5 customers with the highest number of orders for each state.
-- Challenge: Include the number of orders and total sales for each customer.

WITH customer_order_summary AS (
    SELECT 
        c.state,
        c.customer_id,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        COUNT(o.order_id) AS total_orders,
        SUM(oi.total_sale) AS total_sale,
        DENSE_RANK() OVER (
            PARTITION BY c.state 
            ORDER BY COUNT(o.order_id) DESC
        ) AS rank
    FROM orders AS o
    JOIN customers AS c ON o.customer_id = c.customer_id
    JOIN order_items AS oi ON oi.order_id = o.order_id
    GROUP BY c.state, c.customer_id, c.first_name, c.last_name
)

SELECT 
    state,
    customer_id,
    customer_name,
    total_orders,
    total_sale,
    rank
FROM customer_order_summary
WHERE rank <= 5
ORDER BY state, rank;
-- 17. Revenue by Shipping Provider
-- Calculate total revenue, total orders, and average delivery time per provider.

-- Revenue by Shipping Provider (corrected with assumed 'shipping' table)

SELECT 
    s.shipping_providers,
    COUNT(DISTINCT o.order_id) AS total_orders_handled,
    SUM(oi.total_sale) AS total_revenue,
    COALESCE(
        AVG(DATEDIFF(DAY, s.shipping_date, s.return_date)), 0
    ) AS average_delivery_days
FROM orders AS o
JOIN order_items AS oi ON oi.order_id = o.order_id
JOIN shipping AS s ON s.order_id = o.order_id
GROUP BY s.shipping_providers
ORDER BY total_revenue DESC;

-- 18. Top 10 Products with Highest Decreasing Revenue Ratio (2022 vs. 2023)

WITH last_year_sale AS (
    SELECT 
        p.product_id,
        p.product_name,
        cat.category_name,
        SUM(oi.total_sale) AS revenue_2022
    FROM orders AS o
    JOIN order_items AS oi ON oi.order_id = o.order_id
    JOIN products AS p ON p.product_id = oi.product_id
    JOIN category AS cat ON cat.category_id = p.category_id
    WHERE YEAR(o.order_date) = 2022
    GROUP BY p.product_id, p.product_name, cat.category_name
),
current_year_sale AS (
    SELECT 
        p.product_id,
        SUM(oi.total_sale) AS revenue_2023
    FROM orders AS o
    JOIN order_items AS oi ON oi.order_id = o.order_id
    JOIN products AS p ON p.product_id = oi.product_id
    WHERE YEAR(o.order_date) = 2023
    GROUP BY p.product_id
)

SELECT TOP 10
    ls.product_id,
    ls.product_name,
    ls.category_name,
    ls.revenue_2022,
    cs.revenue_2023,
    ROUND(
        (CAST(cs.revenue_2023 - ls.revenue_2022 AS FLOAT) / NULLIF(ls.revenue_2022, 0)) * 100, 
        2
    ) AS revenue_decrease_ratio
FROM last_year_sale AS ls
JOIN current_year_sale AS cs ON ls.product_id = cs.product_id
WHERE cs.revenue_2023 < ls.revenue_2022
ORDER BY revenue_decrease_ratio DESC;

/*
19. Calculate the monthly repeat purchase rate — the percentage of customers
in each month who made more than one purchase in that same month
*/

WITH customer_monthly_orders AS (
    SELECT 
        c.customer_id,
        YEAR(o.order_date) AS order_year,
        MONTH(o.order_date) AS order_month,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM orders AS o
    JOIN customers AS c ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, YEAR(o.order_date), MONTH(o.order_date)
),
monthly_summary AS (
    SELECT 
        order_year,
        order_month,
        COUNT(DISTINCT customer_id) AS total_customers,
        COUNT(CASE WHEN order_count > 1 THEN 1 END) AS repeat_customers
    FROM customer_monthly_orders
    GROUP BY order_year, order_month
)

SELECT 
    order_year,
    order_month,
    total_customers,
    repeat_customers,
    ROUND(CAST(repeat_customers AS FLOAT) * 100.0 / NULLIF(total_customers, 0), 2) AS repeat_rate
FROM monthly_summary
WHERE total_customers >= 10
ORDER BY order_year, order_month;

/*
20.For each customer, find the order that took the longest to ship (from order_date to shipping_date).
*/

WITH shipping_duration AS (
    SELECT 
        c.customer_id,
        o.order_id,
        s.shipping_providers,
        DATEDIFF(DAY, o.order_date, s.shipping_date) AS days_to_ship,
        ROW_NUMBER() OVER (
            PARTITION BY c.customer_id 
            ORDER BY DATEDIFF(DAY, o.order_date, s.shipping_date) DESC
        ) AS rn
    FROM customers AS c
    JOIN orders AS o ON c.customer_id = o.customer_id
    JOIN shipping AS s ON o.order_id = s.order_id
)

SELECT 
    customer_id,
    order_id,
    shipping_providers,
    days_to_ship
FROM shipping_duration
WHERE rn = 1
ORDER BY days_to_ship DESC;
